# Name of the package if any. Package.ModuleName will be the module name 
package_name = "h5"

# The documentation string of the module. 
documentation = '''Python bindings for the TRIQS/h5 library.'''

# Namespace. 
# Only the classes/functions/enums declared in this namespace will be wrapped
namespaces = "h5"

# Match/reject elements according to regex
# If match_names/match_names are both set, filter for all elements 
# Algorithm is (for an element X of fully qualified name Qname)
#    if match_names and not match_names match Qname : skip X
#    if reject_names and reject_names match Qname : skip X
#    else keep X.

match_names = "h5::(group|file|h5_write_bare|h5_read_bare)"
reject_names = "from_borrowed|open_dataset|create_dataset"

# Only keep elements declared in files matching the pattern
# match_files = "" # String must be a regex

exclude_system_headers = false
wrap_no_arg_methods_as_properties = false